### ISSUE TITLE
为什么创建账号可以，转账却不行呢？

### ISSUE THREAD

**Issue by aoctor** [wypeng2012/EOSForJava#1]
你好，感谢你写了这么好的代码，请教一下，我用你的代码在EOS主网上创建账号可以成功。但在转账的的时候，contractaccount 那里总是不认，提示：Internal Service Error。如果我输入“eosio”或者转出账号，就提示转出成功，在转出账号里可以看到一行记录：

52423... | 2019-01-09 15:00:12 | transfere0ec34eeb1697443a069c3a66197947e010000000000000002464149520000000474657374
-- | -- | --
但实际上什么都没有转出去，接收账号那边就什么都看不到。
如果输入“eosio.token”或其他各种合约账号，就不认，是什么原因呢？
我该如何解决呢？

**Comment by wypeng2012** [comment]
> 你好，感谢你写了这么好的代码，请教一下，我用你的代码在EOS主网上创建账号可以成功。但在转账的的时候，contractaccount 那里总是不认，提示：Internal Service Error。如果我输入“eosio”或者转出账号，就提示转出成功，在转出账号里可以看到一行记录：
> 
> 52423...	2019-01-09 15:00:12	transfere0ec34eeb1697443a069c3a66197947e010000000000000002464149520000000474657374
> 但实际上什么都没有转出去，接收账号那边就什么都看不到。		
> 如果输入“eosio.token”或其他各种合约账号，就不认，是什么原因呢？		
> 我该如何解决呢？

应该是你创建账户的时候填写的creator参数填写的不对，不能填写eosio，这个是测试用的，正式环境要填写帮你创建账户被扣费的eos用户的account
